name: DeepLearning

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
    - tensorflow==2.20.0
    - numpy==2.2.6
    - pandas==2.2.3
    - matplotlib==3.10.1
    - seaborn==0.13.2
    - scikit-learn==1.6.1
    - jupyter
    - ipykernel
